In [37]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [38]:
def anos2deci(anos,meses):
    anos_decimais = anos + (meses - 1) /12
    return anos_decimais

In [50]:
def dados2graf(arquivo):
    dados = np.loadtxt(arquivo,comments='%')
    anos = dados[:,0]
    meses = dados[:,1]
    anos_decimais = anos2deci(anos,meses)
    anomalia_temperatura_anual = dados[:,4]
    anomalia_temperatura_10anos = np.nan_to_num(dados[:,8])
    incerteza_anomalia_temperatura_10anos = np.nan_to_num(dados[:,9])
    return(anos_decimais,anomalia_temperatura_anual,anomalia_temperatura_10anos,incerteza_anomalia_temperatura_10anos)

In [51]:
dados2graf("dados/0.80S-49.02W-TAVG-Trend.txt")

(array([ 1845.        ,  1845.08333333,  1845.16666667, ...,  2013.5       ,
         2013.58333333,  2013.66666667]),
 array([   nan,    nan, -0.872, ...,    nan,    nan,    nan]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0., ...,  0.,  0.,  0.]))